# Generated by Django 2.1.7 on 2019-03-31 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Nombre')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='UUID')),
                ('code', models.CharField(max_length=32, verbose_name='Código')),
                ('address', models.CharField(max_length=128, verbose_name='Dirección')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Nombre')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='UUID')),
                ('trs_type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Salida')], max_length=5, verbose_name='Tipo de transacción')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
