# Generated by Django 2.1.7 on 2019-03-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('uuidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.UUIDModel')),
                ('code', models.CharField(max_length=32, verbose_name='Código')),
                ('address', models.CharField(max_length=128, verbose_name='Dirección')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            bases=('core.uuidmodel',),
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('uuidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.UUIDModel')),
                ('trs_type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Salida')], max_length=5, verbose_name='Tipo de transacción')),
            ],
            bases=('core.uuidmodel',),
        ),
    ]
