# Generated by Django 2.1.7 on 2019-03-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='trs_type',
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Salida')], default='', max_length=5, verbose_name='Tipo de Transacción'),
            preserve_default=False,
        ),
    ]
