# Generated by Django 2.1.7 on 2019-03-31 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Nombre')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='UUID')),
                ('document_number', models.CharField(max_length=32, unique=True, verbose_name='Número de documento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
