# Generated by Django 2.1.7 on 2019-03-31 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('uuidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.UUIDModel')),
                ('document_number', models.CharField(max_length=32, unique=True, verbose_name='Número de documento')),
            ],
            bases=('core.uuidmodel',),
        ),
    ]
