# Generated by Django 2.1.7 on 2019-03-31 21:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Nombre')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='UUID')),
                ('code', models.CharField(max_length=32, verbose_name='Código')),
                ('address', models.CharField(max_length=128, verbose_name='Dirección')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Entidad', verbose_name='Entidad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
