# Generated by Django 2.1.7 on 2019-03-31 21:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Nombre')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='UUID')),
                ('e_type', models.CharField(choices=[('PER', 'Persona'), ('EMP', 'Empresa'), ('ORG', 'Organización')], max_length=3, verbose_name='Tipo de entidad')),
                ('d_type', models.CharField(choices=[('DNI', 'DNI - Documento nacional de identidad'), ('EMP', 'RUC - Registro único tributario')], max_length=3, verbose_name='Tipo Documento')),
                ('document_number', models.CharField(max_length=32, unique=True, verbose_name='Número de documento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntidadCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exiled', models.BooleanField(default=False, verbose_name='Exiliado')),
                ('exile_reason', models.TextField(verbose_name='Razón de exilio')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Entidad')),
            ],
        ),
    ]
