# Generated by Django 2.1.7 on 2019-03-31 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exiled', models.BooleanField(default=False, verbose_name='Exiliado')),
                ('exile_reason', models.TextField(verbose_name='Razón de exilio')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Entidad')),
            ],
        ),
    ]
